###########
# site.title

title: Jianwei Li
description: a minimal, text focused blog theme
# baseurl: "/jekyllBear" # the subpath of your site, e.g. /blog/
url: "lijianweicode.github.io" # the base hostname & protocol for your site
# host: 0.0.0.0


#########################
# more settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
# permalink: /blog/:slug
timezone: China/Beijing
future: true


exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

links:
  - title: About Me
    url: /
  - title: Resume
    url: /file/CV-HanlinCAI.pdf
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/
  - title: Fundings
    url: /fundings/
  - title: Hobbies
    url: /hobbies/
  - title: Blogs
    url: /blog/


  

# Add links for more focus here
# special_links:
#   "Search": https://duckduckgo.com